project:
  type: website
  output-dir: _site

website:
  title: "Quant"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Theory
        menu:
          - href: theory/part_1_discrete.qmd
            text: Part I:Intro to Quant Finance
          - href: theory/part_2_continuous.qmd
            text: Part II:Continuous-time Finance
      - text: Projects
        menu:
          - href: projects/project_a.qmd
            text: Project A
      - text: Applications
        menu:
          - href: applications/backtesting.qmd
            text: Backtesting
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: mathjax
    css: styles.css

execute:
  freeze: auto
